platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

inputs:
  - name: git-repo
  - name: version

outputs:
  - name: build

run:
  path: git-repo/ci/tasks/build-artifact.sh
